### ISSUE TITLE
Man, something went wrong...

### ISSUE THREAD

**Issue by krisszzzz** [KetchuppOfficial/Stack#1]
I've experimented with your stack. Here's some sample code. As I understand it, a double call to the constructor should raise a **warning** at least. But here, for some reason, nothing is output to the log file. No idea why. Well, good luck at debugging, man.

main.cpp

`#include "Stack.h"
#include "Log_File.h"

int main (void)
{
    atexit (Close_Log_File);
    if (Open_Log_File () == ERROR)
        return EXIT_FAILURE;

    struct Stack stack = {};

    STACK_CTOR (&stack);

    STACK_PUSH (&stack, 22);

    STACK_PUSH (&stack, 1);

    STACK_PUSH (&stack, 2004);

    FILE* log_file = fopen("log_file.txt", "w");

    for(int i = 0; i < 1000; ++i)
    {
        STACK_PUSH(&stack, i);
        STACK_CTOR(&stack);
        Stack_Dump(&stack, log_file);
        STACK_DTOR(&stack);
    }

    Stack_Dump(&stack, log_file);

    STACK_DTOR (&stack);

    return 0;
}
`

**Comment by KetchuppOfficial** [comment]
I have no idea what have you done, but when I ran this piece of code on my computer, there really was an error report in the log file. It looks like this:
**********************************************************************
This is log file of the project "Hamlet Sorting".
This file will help you to find and fix all the errors.

File: D:\Progamming\C\Stack\Stack.cpp
Line: 9
Function with error: Stack_Ctor
Variable or function that caused error: stack_ptr->initialized
Error description: It's forbidden to initialize stack more than once

File: D:\Progamming\C\Stack\main.cpp
Line: 25
Function with error: main
Variable or function that caused error: Stack_Ctor ()
Error description: Constructing error
**********************************************************************
